### ISSUE TITLE
Try out Lightyear in larger apps

### ISSUE THREAD

**Issue by Ephem** [Ephem/react#14]
So far Lightyear has mainly been tested in different smaller contexts and not a larger application. Tests do give good confidence it is working as expected, but some bugs only manifest in more complex environments, so it would be nice to try it out in a larger application.

I intend to do this with the application I build at work, but it would be very nice to have more data points! Since very few, if any, larger projects are using Suspense for data fetching together with a custom SSR-setup today, the easiest way to help out by testing this is probably if you have a custom SSR-setup with traditional data-fetching (Next.js sadly doesn't support custom renderers like this one).

The thing that differs most from the official server renderer is that when a suspend happens, the rest of that subtree will be rendered by a "child renderer" when the data comes back. Most bugs will probably stem from this fact. A good way to artificially stress-test Lightyear in a larger application would therefor be to fetch data via Suspense in a single top level-isch component, causing most of the application to be rendered by a child renderer. A partial refactor to fetch the real application-data with Suspense would also be very helpful of course, but a much larger time investment (unless you already use `react-apollo-hooks`, in which case it could be feasible).

Looking at the examples should give you a hint of how to go about this, but I would also be extremely happy to help out in any way I can!

**Comment by albertogasparin** [comment]
FYI I've tried it in a large app and it worked fine. Found a couple of problems (reported here) but other than that was able to have the SSR server stream the output in a day. So good work!

**Comment by Ephem** [comment]
That makes me so happy! Thanks for trying it out and filing those issues, they were exactly the kind of things I suspected would show up. I'll take a look at them asap. :)

**Comment by Ephem** [comment]
@albertogasparin The issues you reported have since been solved.

I've also tried Lightyear at work (a pretty big site), rendering with both the official renderer and Lightyear and comparing outputs, I found no diffs.

On top of that I've heard from more people trying this out with success. While there might of course still be bugs and I'd love for more people to try it out and file issues, I now consider Lightyear having been tried out in enough applications to close this issue.

Huge thanks again for the help!

**Comment by albertogasparin** [comment]
Wonderful, unfortunately I didn't have time to test it again as the work was done during "innovation time" so it was more like a one off experiment. But I hope to have time to get back to it in the upcoming months for a second go ;)
Amazing stuff and thanks again!
