### ISSUE TITLE
Update supporting doc files

### ISSUE THREAD

**Issue by voxpelli** [Ephem/react#2]
Some suggestion:

* `CHANGELOG.md` – Start out by describing what changes have been made from the base React project, what the plan is for possibly upstreaming those changes (like a PR/Issue link) and then from there, for each version, just note the differences from the version before
* `CONTRIBUTING.md`– should probably highlight that everything not specific to the changes you have made should be filed against the upstream repo and not here. Only things related to your specific alteration should be reported here (I assume 😉)
* `.github/ISSUE_TEMPLATE.md`+ `.github/PULL_REQUEST_TEMPLATE.md` – evaluate whether these should also be updated

**Comment by Ephem** [comment]
Excellent suggestions, thanks! Will definitely update these.

Besides supporting docs I think there are a lot more tweaks to be made to the repo to make it polished, clearer and easier to maintain. I’m figuring this out as I go so keep the feedback coming if you see things, it’s super valuable! :)

**Comment by Ephem** [comment]
Updated supporting docs in #4. They can probably be improved further, but hopefully things are a bit clearer now! Thanks again for reporting. :)
